# Generated by Django 4.1.3 on 2023-04-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera",
            old_name="camera_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="camera",
            old_name="camera_url",
            new_name="url",
        ),
    ]
