# Generated by Django 4.1.3 on 2023-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_camera_name_camera_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
