# Generated by Django 4.1.3 on 2023-04-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_photo_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="photos",
        ),
        migrations.AddField(
            model_name="photo",
            name="employee",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="core.employee",
            ),
            preserve_default=False,
        ),
    ]
